### PR TITLE
Run CI tests with pytest-xdist

### LINKED ISSUE #99: multithreaded runtests.py
bc.. It should be trivial to run several tests at once using Parallel Python or
something else. py.test offers such a feature already, so maybe we should
use it instead of a own solution.

p. Original issue for "#99":https://github.com/fredrik-johansson/mpmath/issues/99: "http://code.google.com/p/mpmath/issues/detail?id=59":http://code.google.com/p/mpmath/issues/detail?id=59

p. Original author: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

p. Original owner: "https://code.google.com/u/Vinzent.Steinberg@gmail.com/":https://code.google.com/u/Vinzent.Steinberg@gmail.com/

### PR DESCRIPTION
**Pull request by skirpichev**
Closes #99

### CODE REVIEW

**Comment by oscarbenjamin** [comment]
Obviously it is useful to be able to run the tests in parallel locally so this is good.

When I've tried to use `pytest-xdist` before in CI though it hasn't seemed to bring the expected speed up in CI itself. I think GA runners only have two cores and I guess there's just too much overhead in the main thread to get the benefit of distributing the work over two threads. I guess it doesn't hurt though and it is good to ensure that being able to run the tests in parallel is itself tested in CI.

One potential downside is that if the tests fail because of something hanging then it can be difficult to know from the xdist output which test has failed which is particularly awkward if the failure is seen in CI but not locally. I haven't found anything better for this than using pytest's verbose mode to print out each test name as it starts and finishes.

**Comment by skirpichev** [comment]
> it hasn't seemed to bring the expected speed up in CI itself

Well, we have 5-8 min in this pr for py3.10/11 and 8-11 in the master.

> I guess it doesn't hurt though and it is good to ensure that being able to run the tests in parallel is itself tested in CI.

And we can drop workarounds for resetting globals (dps, prec, etc).

> One potential downside is that if the tests fail because of something hanging then it can be difficult to know from the xdist output which test has failed

I don't think it's a special downside of the xdist plugin.  Same will be for plain pytest.

> I haven't found anything better for this than using pytest's verbose mode to print out each test name as it starts and finishes.

Probably we could use the pytest-timeout plugin with some "big enough" default.

**Comment by oscarbenjamin** [comment]
> Well, we have 5-8 min's in this pr for py3.10/11 and 8-11 in the master.

Okay, that's good. That didn't happen when I tried before.

> I don't think it's a special downside of the xdist plugin. Same will be for plain pytest.

No because plain pytest shows which test module it is currently working on and how many tests have already run like:
```
mpmath/usertools.py .                                                    [ 16%]
mpmath/visualization.py .                                                [ 17%]
mpmath/calculus/approximation.py ..                                      [ 17%]
mpmath/calculus/differentiation.py .....
```
With xdist the default output is just
```
gw0 I / gw1 I
gw0 [632] / gw1 [632]

........................................................................ [ 11%]
........................................................................ [ 22%]
........................................................................ [ 34%]
........................................................................ [ 45%]
........................................................................ [ 56%]
........................................................................ [ 68%]
........................................................................ [ 79%]
.......................................x.......s...................x.... [ 91%]
........................................................                 [100%]
```
If one of the two workers hangs then the other will complete the test suite and it will just show that it's stuck at 99%.

> Probably we could use the pytest-timeout plugin with some "big enough" default.

That's probably a better idea. None of the tests here take that long.

**Comment by oscarbenjamin** [comment]
> And we can drop workarounds for resetting globals (dps, prec, etc).

Maybe it would be better not to have tests/doctests that modify the globals in the first place (i.e. gh-683).

**Comment by skirpichev** [comment]
> mpmath/calculus/differentiation.py .....
> vs
> ........................................................                 [100%]

Neither variant shows a test that hangs.

> That's probably a better idea.

But I doubt we should add such dependency right now.

> Maybe it would be better not to have tests/doctests that modify the globals in the first place (i.e. https://github.com/mpmath/mpmath/issues/683).

Sure, but that's a different issue.

**Pull request merged**
