### PR TITLE
Drop private mpq class, use Rational's, provided by backend

### PR DESCRIPTION
**Pull request by skirpichev**
* Missing feature (for pure-python) is an additional caching mechanism.  Not sure it worth.
* Unfortunately, gmpy2 has no released version with support for mpq.as_numer_denom(), hence I use foo.numerator/denominator to unpack components of rationals...  Edit: the numbers.Rational doesn't require this method, so we could not rely on it.

### CODE REVIEW

**Comment by skirpichev** [comment]
Missing feature (for pure-python) is additional caching mechanism.

**Comment by oscarbenjamin** [comment]
This looks good to me.

I don't know how significant the caching mechanism is but it does not look as if there are any places where `MPQ` is used in a tight loop.

**Comment by skirpichev** [comment]
@oscarbenjamin, I've some doubts about the ctx.mpq attribute.  It's not documented, but apparently people discover it and use (e.g. #532).  Maybe we should keep this and issue a deprecation warning before removing?

**Comment by oscarbenjamin** [comment]
> Maybe we should keep this and issue a deprecation warning before removing?

Oh, I didn't notice that this removes the `ctx.mpq` attribute as well as `ctx._mpq`. I would say that as long as `MPQ` exists then it is harmless to just leave `ctx.mpq` as an alias to it. If there is no significant gain in removing it then I don't see any need to deprecated it.

**Comment by skirpichev** [comment]
> to just leave ctx.mpq as an alias to it.

mpq is a special attribute for the MPContext() only.

> If there is no significant gain in removing

Slightly better API?

**Pull request merged**
