### PR TITLE
Add hypothesis-based formatting tests and workaround #858

### LINKED ISSUE #858: format(mp.mpf(0.99999), '.4f') returns '0.99999'
Should be '1.0000'.

I would guess this is related to "a hack" here:
https://github.com/mpmath/mpmath/blob/9d9029a5592124670dd6efd89c26b0c2304d272e/mpmath/libmp/libmpf.py#L1519-L1522

CC @javierelpianista

### PR DESCRIPTION
**Pull request by skirpichev**
* fix also few other minor issues, coming from tests, closes #858
* simplify handling '%' format type
* split out format_digits() and redo handling special numbers

### CODE REVIEW

**Comment by javierelpianista** [comment]
This is better but still fails in some cases, for example,
```python
>>> format(mp.mpf('0.99'), '.1f')
'1.'
>>> format(mp.mpf('0.999'), '.2f')
'1.0'
```

The reason is that `to_digits_exp` not always produces a string of 9s.
For example,
```python
>>> to_digits_exp(mp.mpf(0.99)._mpf_, 15)
('', '989999999999999991', -1)
>>> to_digits_exp(mp.mpf(0.999)._mpf_, 15)
('', '998999999999999999', -1)
```.

The solution is to improve the hack to take into account the cases where the last rounded digit is not a 9, but one of the digits that would be rounded up.
I've made a separate PR for this. #860

**Comment by skirpichev** [comment]
> I've made a separate PR for this

Thanks, I've cherry-picked some commits from that pr and did some cleanup for the fix.

**Comment by skirpichev** [comment]
On another hand, ``format(mp.mpf(0.96875), '#.0g')`` now returns ``1.0``, where Python shows ``1.``.

**Comment by skirpichev** [comment]
I did rebase.  Now first commit include fix for https://github.com/mpmath/mpmath/issues/858, including https://github.com/mpmath/mpmath/pull/860.  The 'g' format also fixed.

**Comment by skirpichev** [comment]
@javierelpianista, are you ok with this or prefer https://github.com/mpmath/mpmath/pull/860?

**Comment by javierelpianista** [comment]
> @javierelpianista, are you ok with this or prefer #859 

I'm OK with this!

**Pull request merged**
