### PR TITLE
Misc fixes

### LINKED ISSUE #471: bernpoly behaviour at infinity with 0 imaginary component
Good:
```
>>> inf = float('inf')
>>> mpmath.bernpoly(3, inf)                                                        
mpf('+inf')

>>> mpmath.bernpoly(4, inf)                                                        
mpf('+inf')
```

Now how about complex with 0 imag part?  This seems ok:
````
>>> bernpoly(4, complex(inf, 0))
mpc(real='+inf', imag='0.0')
```
But:
```
>>> bernpoly(3, complex(inf, 0))
mpc(real='nan', imag='nan')
````
This isn't wrong per se if you think of `complex(..., 0)` as a very small negative part.

Do we care?  Correct behaviour at real infinity is very nice property but maybe exactly what happens for `complex(..., 0)` is less important?

### LINKED ISSUE #472: bernpoly complex limit
The magnitude of this evaluation is completely wrong:
```
>>> bernpoly(4, complex(inf, 1e-50))
mpc(real='9.9999999999999998e-201', imag='0.0')
```
compared to:
```
>>> bernpoly(4, complex(1e5, 1e-5))                                         
mpc(real='9.9998000010000007e+19', imag='39999400002.0')

>>> bernpoly(4, complex(1e50, 1e-50))                                       
mpc(real='1.0000000000000003e+200', imag='4.0000000000000008e+100')
```
(probably related to #471).

Other tests:
```
>>> bernpoly(4, complex(inf, 2))                                            
mpc(real='16.0', imag='0.0')

>>> bernpoly(4, complex(inf, 3))                                            
mpc(real='81.0', imag='0.0')
```
(again the values should  inf or nan, or at least big)

### LINKED ISSUE #836: `mpmath/tests/test_convert.py::test_compatibility` fails on ppc64, sparc (possibly more)
While testing on PPC64 and SPARC, we've noticed the following test failure that seems to be related to longdouble precision:

```pytb
$ python -m pytest mpmath/tests/test_convert.py::test_compatibility  -vv
========================================================= test session starts =========================================================
platform linux -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0 -- /home/mgorny/mpmath/.venv/bin/python
mpmath backend: python
mpmath mp class: <mpmath.ctx_mp.MPContext object at 0x3fff9c72fe60>
mpmath version: 1.4.0a2.dev67+gcf98bcf
Python version: 3.12.3 (main, May 31 2024, 13:52:31) [GCC 12.3.1 20230526]
cachedir: .pytest_cache
rootdir: /home/mgorny/mpmath
configfile: pyproject.toml
plugins: xdist-3.6.1
collected 1 item                                                                                                                      

mpmath/tests/test_convert.py::test_compatibility FAILED                                                                         [100%]

============================================================== FAILURES ===============================================================
_________________________________________________________ test_compatibility __________________________________________________________

    def test_compatibility():
        from packaging.version import Version, parse
        np = pytest.importorskip("numpy")
        if parse(np.__version__) < Version('2.0.0b1'):
            npcore = np.core
        else:
            npcore = np._core
        # numpy types
        for nptype in npcore.numerictypes.typeDict.values():
            if issubclass(nptype, np.complexfloating):
                x = nptype(complex(0.5, -0.5))
            elif issubclass(nptype, np.floating):
                x = nptype(0.5)
            elif issubclass(nptype, np.integer):
                x = nptype(2)
            # Handle the weird types
            try: diff = np.abs(type(np.sqrt(x))(sqrt(x)) - np.sqrt(x))
            except: continue
            assert diff < np.float64(2.0**-53)
        assert mpf(np.float64('inf')) == inf
        assert isnan(mp.npconvert(np.float64('nan')))
        if hasattr(np, "float128"):
            mp.prec = 113
>           assert (mp.npconvert(np.float128('0.841470984807896506652502321630298954')) ==
                    mpf('0.841470984807896506664590813295845351'))
E           AssertionError: assert mpf('0.841470984807896506652502321630296065') == mpf('0.841470984807896506664590813295845351')
E            +  where mpf('0.841470984807896506652502321630296065') = npconvert(np.longdouble('0.8414709848078965066525023216303'))
E            +    where npconvert = <mpmath.ctx_mp.MPContext object at 0x3fff9c72fe60>.npconvert
E            +    and   np.longdouble('0.8414709848078965066525023216303') = <class 'numpy.longdouble'>('0.841470984807896506652502321630298954')
E            +      where <class 'numpy.longdouble'> = <module 'numpy' from '/home/mgorny/mpmath/.venv/lib/python3.12/site-packages/numpy/__init__.py'>.float128
E            +  and   mpf('0.841470984807896506664590813295845351') = mpf('0.841470984807896506664590813295845351')

mpmath/tests/test_convert.py:267: AssertionError
======================================================== slowest 20 durations =========================================================
0.14s call     mpmath/tests/test_convert.py::test_compatibility
0.00s setup    mpmath/tests/test_convert.py::test_compatibility
0.00s teardown mpmath/tests/test_convert.py::test_compatibility
======================================================= short test summary info =======================================================
FAILED mpmath/tests/test_convert.py::test_compatibility - AssertionError: assert mpf('0.841470984807896506652502321630296065') == mpf('0.841470984807896506664590813295845351')
 +  where mpf('0.841470984807896506652502321630296065') = npconvert(np.longdouble('0.8414709848078965066525023216303'))
 +    where npconvert = <mpmath.ctx_mp.MPContext object at 0x3fff9c72fe60>.npconvert
 +    and   np.longdouble('0.8414709848078965066525023216303') = <class 'numpy.longdouble'>('0.841470984807896506652502321630298954')
 +      where <class 'numpy.longdouble'> = <module 'numpy' from '/home/mgorny/mpmath/.venv/lib/python3.12/site-packages/numpy/__init__.py'>.float128
 +  and   mpf('0.841470984807896506664590813295845351') = mpf('0.841470984807896506664590813295845351')
========================================================== 1 failed in 0.34s ==========================================================
```

To reproduce (on PPC64 or SPARC):

```
pip install -e . pytest numpy
python -m pytest mpmath/tests/test_convert.py::test_compatibility
```

Not sure if it's a matter of better or worse precision, though.

### LINKED ISSUE #838: `[doctest] mpmath.calculus.optimization.steffensen` fails on alpha in 1.4.0a1
On alpha processor:

```pytb
================================== FAILURES ==================================
_____________ [doctest] mpmath.calculus.optimization.steffensen ______________
1034 
1035     x* is a fixpoint of the iteration x_{k+1} = phi(x_k) if x* = phi(x*). For
1036     phi(x) = x**2 there are two fixpoints: 0 and 1.
1037 
1038     Let's try Steffensen's method:
1039 
1040     >>> f = lambda x: x**2
1041     >>> from mpmath.calculus.optimization import steffensen
1042     >>> F = steffensen(f)
1043     >>> for x in [0.5, 0.9, 2.0]:
Differences (unified diff with -expected +actual):
    @@ -5,5 +5,5 @@
              2.32831e-10          -2.84465e-27
              5.42101e-20           2.30189e-80
    -         2.93874e-39          -1.2197e-239
    +         2.93874e-39                     0
              8.63617e-78                     0
             7.45834e-155                     0

/var/tmp/portage/dev-python/mpmath-1.4.0_alpha1/work/mpmath-1.4.0a1/mpmath/calculus/optimization.py:1043: DocTestFailure
```

This was tested against 1.4.0a1. This has been tested by a volunteer, but I'm going to try getting access to the box, and testing on git.

### LINKED ISSUE #840: [doc] recommend gmpy2 instead of gmpy
https://mpmath.org/doc/current/setup.html#using-gmpy-optional recommends using `gmpy` but does not say how to install that package. It would be helpful to indicate that up-to-date pip package is called `gmpy2` (https://pypi.org/project/gmpy2/), whereas "pip install gmpy" fails with complaints about missing `longintrepr.h` or other, obscure compiler errors.

### PR DESCRIPTION
**Pull request by skirpichev**
* drop special import for random
* fix MPZ_ONE import
* normalize mpf in mp.npconvert() and lower precision in tests, closes #836
* use mpf's in steffensen() doctest, closes #838
* move up special cases in bernpoly(), closes #471
* skip special case in mpc_pow_int() for special numbers, closes #472
* clarify gmpy2 support, closes #840
* pin numpy (<2.1)

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks. I did a quick test on AArch64, and it seems to work as well.

**Comment by skirpichev** [comment]
I would appreciate if you could test all affected (from issues) platforms.  Unfortunately, this is not tested in our CI.

**Comment by mgorny** [comment]
No problem. I was in a bit of a hurry in the morning but now I've run the whole test suite on all three systems, with gmpy and python backends, and all tests passed.

**Comment by mgorny** [comment]
Sorry, to be clear: I've tested aarch64, ppc64le and sparc. Unfortunately, I don't have direct access to alpha. I'll ping someone if they could test it but it'll probably take a few days, so you may want to proceed without waiting.

**Comment by skirpichev** [comment]
> it but it'll probably take a few days

I think it's not urgent, so I'll wait.

**Comment by skirpichev** [comment]
See also https://github.com/numpy/numpy/issues/10288.  Maybe numpy test should explicitly use np.longdouble.

**Pull request merged**
