### PR TITLE
Change FPContext to use more functions from the stdlib

### PR DESCRIPTION
**Pull request by skirpichev**
* use math.erf, math.erfc, math.gamma
* use math.atan2
* use cmath.phase for fp.arg
* reorganize input handling in e1() and ei()
* remove unused code in math2.py
* use constants, e.g. math.inf or math.nan
* move most constants to the mpmath/ctx_fp.py
* move mpmath/math2.py -> mpmath/libfp.py, closes https://github.com/mpmath/mpmath/issues/211

### CODE REVIEW

**Comment by cbm755** [comment]
have not tested but reading over the changes, this LGTM

**Comment by skirpichev** [comment]
There is a [test failure](https://github.com/mpmath/mpmath/actions/runs/4912783614/jobs/8772191829) for PyPy jobs, see changed doctest.  It is due to using a custom erf/erfc implementations in PyPy (CPython uses libm's versions).  But I think that CPython's value is better:
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> math.erfc(2.5)
0.0004069520174449589
$ pypy3
Python 3.7.10 (7.3.5+dfsg-2+deb11u2, Nov 01 2022, 20:16:36)
[PyPy 7.3.5 with GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import math
>>>> math.erfc(2.5)
0.00040695201744495903
>>>> 
$ wolframscript 
Wolfram Language 13.2.0 Engine for Linux x86 (64-bit)
Copyright 1988-2022 Wolfram Research, Inc.

In[1]:= Erfc[2.5``21]                                                                                                                                          

Out[1]= 0.0004069520174449589

In[2]:= Erfc[2.5``22]                                                                                                                                          

Out[2]= 0.00040695201744495894

In[3]:= Erfc[2.5``25]                                                                                                                                          

Out[3]= 0.00040695201744495893956
```

Perhaps, alternatively (wrt using ELLIPSIS option) we could use a different argument value, say 0.5...

**Comment by skirpichev** [comment]
@cbm755 is this better or worse?

**Comment by oscarbenjamin** [comment]
Looks good to me.

**Comment by skirpichev** [comment]
Ok, I did rebase (no changes).  Then I'll merge this.

**Pull request merged**
