### PR TITLE
Remove sage backend

### LINKED ISSUE #574: Commit 84ca137ff84f7b3d22cabcf8bfe260146db4defe breaks running distro-provided sagemath
Since commit 84ca137ff84f7b3d22cabcf8bfe260146db4defe (pr #466) the SAGE_ROOT variable presence is used to detect whether mpmath is being used from sage. But that variable is only set when running sage installed via the Sage distribution, and not when running distro packages.

### LINKED ISSUE #705: Test sage integration or remove sage backend
We have a special value 'sage' for the BACKEND global variable.  If this is a part of the mpmath codebase - this should be tested with our regular CI tests.

### PR DESCRIPTION
**Pull request by skirpichev**
Closes #705
Closes #574

### CODE REVIEW

**Comment by tornaria** [comment]
This breaks sagemath (which sets `MPMATH_SAGE=1` in the environment and expects the mantissa to be of type `sage.rings.integer.Integer`. I'm testing with mpmath 1.4.0a0, now that sympy 1.12.1a1 supports it.

Is there a plan on how to move forward sagemath?

cc: @dimpase

**Comment by dimpase** [comment]
@tornaria - I don't recall what the plan was - perhaps just to drop that Sage variable?

**Comment by tornaria** [comment]
> @tornaria - I don't recall what the plan was - perhaps just to drop that Sage variable?

First sagemath has to support mpmath with gmpy2 backend, but I did not find a PR for that (maybe there is none, I just saw this being discussed on #705)

@skirpichev @fredrik-johansson do you have any input about this?

FWIW, I think removing the sage backend is a good move, but some coordination with sagemath seems a good thing.

**Comment by skirpichev** [comment]
> First sagemath has to support mpmath with gmpy2 backend

I don't think we should do anything special for it.  If sage has the gmpy2 module - gmpy2 support for the mpmath will be turned on, unless you disabled it by the MPMATH_NOGMPY environment variable.

**Comment by tornaria** [comment]
> > First sagemath has to support mpmath with gmpy2 backend
> 
> I don't think we should do anything special for it. If sage has the gmpy2 module - gmpy2 support for the mpmath will be turned on, unless you disabled it by the MPMATH_NOGMPY environment variable.

Something has to be done somewhere, since running sagemath with 1.4.0a0 is broken, for instance:
```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.3, Release Date: 2024-03-19                    │
│ Using Python 3.12.2. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: from sage.libs.mpmath.all import sage_to_mpmath, mpmath_to_sage
sage: mpmath_to_sage(sage_to_mpmath(0.0, prec=50), prec=50)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 mpmath_to_sage(sage_to_mpmath(RealNumber('0.0'), prec=Integer(50)), prec=Integer(50))

File /usr/lib/python3.12/site-packages/sage/libs/mpmath/utils.pyx:271, in sage.libs.mpmath.utils.mpmath_to_sage (build/cythonized/sage/libs/mpmath/utils.c:8440)()
    269 if hasattr(x, "_mpf_"):
    270     y = RealField(prec)()
--> 271     mpfr_from_mpfval(y.value, x._mpf_)
    272     return y
    273 elif hasattr(x, "_mpc_"):

File /usr/lib/python3.12/site-packages/sage/libs/mpmath/utils.pyx:166, in sage.libs.mpmath.utils.mpfr_from_mpfval (build/cythonized/sage/libs/mpmath/utils.c:7571)()
    164 cdef long exp
    165 cdef long bc
--> 166 sign, man, exp, bc = x
    167 if man:
    168     mpfr_set_z(res, man.value, MPFR_RNDZ)

TypeError: Cannot convert gmpy2.mpz to sage.rings.integer.Integer
```
Hopefully it's only conversion. As I said, sage is expecting `man` to be a sage integer. Also when going in the other direction sage will use sage integers for the mantissa, maybe this breaks mpmath in other ways.

**Comment by skirpichev** [comment]
I see.  Sage has additional cython replacements for mpmath functions, but this interface is outdated already for the 1.3.0 version (see e.g. https://github.com/sagemath/sage/pull/36447).  I think it might be dropped.

**Comment by dimpase** [comment]
which version of scipy is compatible with this branch?

**Comment by skirpichev** [comment]
> which version of scipy is compatible with this branch?

AFAIC, only the sympy master, since https://github.com/sympy/sympy/pull/26269

**Comment by oscarbenjamin** [comment]
Actually there is sympy 1.12.1a1 that should be compatible:
https://pypi.org/project/sympy/#history

Soon there should be 1.12.1

**Comment by dimpase** [comment]
oh yeah, it's SymPy, not SciPy

**Comment by tornaria** [comment]
> Actually there is sympy 1.12.1a1 that should be compatible: https://pypi.org/project/sympy/#history

Yes, thanks for that. It's why I started testing this only now.

**Comment by oscarbenjamin** [comment]
I don't know how easily this fits your workflow but you might find it easier to track mpmath and sympy master branches. SymPy's master branch tracks mpmath's master branch directly regardless of prereleases:
https://github.com/sympy/sympy/blob/17639a46b648f265c968ea86b78725258024f715/.github/workflows/runtests.yml#L461
It is more likely that the master branches are in sync than that prereleases are.

**Comment by tornaria** [comment]
> I don't know how easily this fits your workflow but you might find it easier to track mpmath and sympy master branches. SymPy's master branch tracks mpmath's master branch directly regardless of prereleases: https://github.com/sympy/sympy/blob/17639a46b648f265c968ea86b78725258024f715/.github/workflows/runtests.yml#L461 It is more likely that the master branches are in sync than that prereleases are.

I track prereleases to have ahead-of-time warning of what will happen with future updates (maiainly sagemath and dependencies, e.g. https://github.com/void-linux/void-packages/pull/49571). Tracking master would be unworkable (and for most projects building from master is a different procedure than building from a release or prerelease, so it wouldn't be testing the same). I dogfood my own draft packages so they have to be in a usable combination.

**Comment by mkoeppe** [comment]
I have the necessary update for Sage in https://github.com/sagemath/sage/pull/38113

**Pull request merged**
